"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import json
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load config from environment variables or fall back to config.json
def get_config(key, default=None):
    """Get config from environment variables first, then from config.json"""
    # Check environment variable first
    env_value = os.environ.get(key)
    if env_value is not None:
        return env_value
    
    # Fall back to config.json if it exists
    try:
        with open(BASE_DIR / 'config.json') as conf_file:
            config = json.load(conf_file)
            return config.get(key, default)
    except FileNotFoundError:
        # In production, config.json is not needed as all config comes from env vars
        if os.environ.get('DJANGO_ENV') == 'production':
            return default
        raise FileNotFoundError(f"The configuration file 'config.json' was not found.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_config('SECRET_KEY', 'django-insecure-changeme')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_config('DEBUG', 'False') in ('True', 'true', '1', 'yes')

ALLOWED_HOSTS = get_config('ALLOWED_HOSTS', '127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'channels',
    'users',
    'word_dash',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Support both MySQL and PostgreSQL
db_engine = get_config('DB_ENGINE', 'django.db.backends.mysql')

DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': get_config('DB_NAME', 'word_dash'),
        'USER': get_config('DB_USER', 'root'),
        'PASSWORD': get_config('DB_PASSWORD', ''),
        'HOST': get_config('DB_HOST', 'localhost'),
        'PORT': get_config('DB_PORT', '3306' if 'mysql' in db_engine else '5432'),
    }
}

# Handle connection pooling for PostgreSQL if needed
if 'postgresql' in db_engine:
    DATABASES['default']['CONN_MAX_AGE'] = 600


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# Email settings
EMAIL_BACKEND = get_config('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = get_config('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_USE_TLS = get_config('EMAIL_USE_TLS', 'True') in ('True', 'true', '1', 'yes')
EMAIL_PORT = int(get_config('EMAIL_PORT', '587'))
EMAIL_HOST_USER = get_config('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = get_config('EMAIL_HOST_PASSWORD', '')


AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'lobby'
LOGOUT_REDIRECT_URL = 'login'

ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND':'channels.layers.InMemoryChannelLayer',
    }
}